## 1- Carga de datos (Seccion 1)

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import os

In [3]:
def cargar_datos(path):
 path_file = 'datos/campanas_creatividad_digital.csv'
 path_complete = os.path.join(os.getcwd(), path_file)
 df = pd.read_csv(path_complete, parse_dates = ['fecha'])
 return df

In [4]:
path = 'datos/campanas_creatividad_digital.csv'
df = cargar_datos(path)

## 2- Estructura del dataset (Seccion 2)

In [5]:
df.head()

,id_campana,fecha,cliente,plataforma,formato,duracion_seg,objetivo,pais,presupuesto_usd,costo_usd,impresiones,alcance,clicks,reproducciones_3s,reproducciones_100,conversiones,ingresos_usd,calificacion_creativa
0,CAMP-0001,2025-01-02,LumaAds,YouTube,Reel,30,Traffic,MX,2449.27,2356.84,319655,212076,4073,171648,26034,82,626.92,79
1,CAMP-0002,2025-01-03,FrameHouse,Facebook,Reel,25,Traffic,AR,1153.08,836.40,185919,103138,3718,88732,22749,93,678.65,93
2,CAMP-0003,2025-01-04,PixelForge,Facebook,Video Largo,60,Ventas,PE,398.93,291.12,50288,27514,488,22772,9557,24,1082.33,63
3,CAMP-0004,2025-01-05,FrameHouse,YouTube,Video Largo,90,Awareness,AR,1752.35,1304.59,279213,210519,2491,177098,29152,19,64.42,69
4,CAMP-0005,2025-01-06,NeoStudio,Instagram,Video Largo,45,Ventas,CL,703.80,640.98,140856,109020,1878,68165,39455,137,5787.29,73

In [6]:
print(f"Filas {df.shape[0]}, Columnas {df.shape[1]}")
print(f"Tipo de datos:\n{df.dtypes}")

Filas 180, Columnas 18
Tipo de datos:
id_campana                          str
fecha                    datetime64[us]
cliente                             str
plataforma                          str
formato                             str
duracion_seg                      int64
objetivo                            str
pais                                str
presupuesto_usd                 float64
costo_usd                       float64
impresiones                       int64
alcance                           int64
clicks                            int64
reproducciones_3s                 int64
reproducciones_100                int64
conversiones                      int64
ingresos_usd                    float64
calificacion_creativa             int64
dtype: object

In [7]:
print(f"Cantidad de valores nulos:\n{df.isna().sum()}")

Cantidad de valores nulos:
id_campana               0
fecha                    0
cliente                  0
plataforma               0
formato                  0
duracion_seg             0
objetivo                 0
pais                     0
presupuesto_usd          0
costo_usd                0
impresiones              0
alcance                  0
clicks                   0
reproducciones_3s        0
reproducciones_100       0
conversiones             0
ingresos_usd             0
calificacion_creativa    0
dtype: int64

In [8]:
columnas_numericas = df.select_dtypes(include=['number','datetime']).columns
print("Columnas numéricas: \n", columnas_numericas)
columnas_categorias = df.select_dtypes(include=['str','category']).columns
print("Columnas de categorias: \n", columnas_categorias)

Columnas numéricas:
 Index(['fecha', 'duracion_seg', 'presupuesto_usd', 'costo_usd', 'impresiones',
       'alcance', 'clicks', 'reproducciones_3s', 'reproducciones_100',
       'conversiones', 'ingresos_usd', 'calificacion_creativa'],
      dtype='str')
Columnas de categorias:
 Index(['id_campana', 'cliente', 'plataforma', 'formato', 'objetivo', 'pais'], dtype='str')

In [9]:
print(f"Primeras 5 filas y ultimas 5 filas del dataframe:\n{df.value_counts()}")

Primeras 5 filas y ultimas 5 filas del dataframe:
id_campana  fecha       cliente     plataforma  formato      duracion_seg  objetivo   pais  presupuesto_usd  costo_usd  impresiones  alcance  clicks  reproducciones_3s  reproducciones_100  conversiones  ingresos_usd  calificacion_creativa
CAMP-0001   2025-01-02  LumaAds     YouTube     Reel         30            Traffic    MX    2449.27          2356.84    319655       212076   4073    171648             26034               82            626.92        79                       1
CAMP-0002   2025-01-03  FrameHouse  Facebook    Reel         25            Traffic    AR    1153.08          836.40     185919       103138   3718    88732              22749               93            678.65        93                       1
CAMP-0003   2025-01-04  PixelForge  Facebook    Video Largo  60            Ventas     PE    398.93           291.12     50288        27514    488     22772              9557                24            1082.33       63                       1
CAMP-0004   2025-01-05  FrameHouse  YouTube     Video Largo  90            Awareness  AR    1752.35          1304.59    279213       210519   2491    177098             29152               19            64.42         69                       1
CAMP-0005   2025-01-06  NeoStudio   Instagram   Video Largo  45            Ventas     CL    703.80           640.98     140856       109020   1878    68165              39455               137           5787.29       73                       1
                                                                                                                                                                                                                                                 ..
CAMP-0176   2025-06-26  LumaAds     YouTube     Carrusel     0             Traffic    CL    1580.90          1038.68    208212       162608   2364    46551              14449               73            526.98        88                       1
CAMP-0177   2025-06-27  LumaAds     Facebook    Imagen       0             Traffic    AR    1942.07          1686.23    343280       179363   5831    87296              25884               167           1424.52       78                       1
CAMP-0178   2025-06-28  CromaLab    YouTube     Imagen       0             Traffic    AR    2561.05          2464.58    383086       218732   5467    95338              36307               163           1392.68       85                       1
CAMP-0179   2025-06-29  CromaLab    Instagram   Story        15            Traffic    CO    2109.14          1511.14    364814       217284   8112    250048             108926              247           2059.09       92                       1
CAMP-0180   2025-06-30  CromaLab    Facebook    Carrusel     0             Leads      MX    3216.03          3156.29    746485       554270   10367   193659             47865               466           10702.31      80                       1
Name: count, Length: 180, dtype: int64

## 3-Indicadores derivados (Seccion 3)

In [10]:
#Indicadores basicos:
df['ctr'] = df['clicks'] / df['impresiones']
df['cvr'] = df['conversiones'] / df['clicks']

#Indicadores de costo
df['cpc'] = df['costo_usd'] / df['clicks']
df['cpm'] = (df['costo_usd']/df['impresiones']) * 1000

#Indicador compuesto
df['roi'] = (df['ingresos_usd'] - df['costo_usd']) / df['costo_usd']

In [13]:
#Verificar que las columnas si den valores
df[['ctr','cvr','cpc','cpm','roi']]

          ctr       cvr       cpc       cpm       roi
0    0.012742  0.020133  0.578650  7.373074 -0.734000
1    0.019998  0.025013  0.224960  4.498733 -0.188606
2    0.009704  0.049180  0.596557  5.789055  2.717814
3    0.008922  0.007627  0.523721  4.672383 -0.950621
4    0.013333  0.072950  0.341310  4.550605  8.028815
..        ...       ...       ...       ...       ...
175  0.011354  0.030880  0.439374  4.988569 -0.492645
176  0.016986  0.028640  0.289184  4.912113 -0.155204
177  0.014271  0.029815  0.450810  6.433490 -0.434922
178  0.022236  0.030449  0.186285  4.142220  0.362607
179  0.013888  0.044950  0.304455  4.228203  2.390788

[180 rows x 5 columns]

In [15]:
#Verificar que las columnas se encuentren en el dataframe
df.head()

,id_campana,fecha,cliente,plataforma,formato,duracion_seg,objetivo,pais,presupuesto_usd,costo_usd,...,reproducciones_3s,reproducciones_100,conversiones,ingresos_usd,calificacion_creativa,ctr,cvr,cpc,cpm,roi
0,CAMP-0001,2025-01-02,LumaAds,YouTube,Reel,30,Traffic,MX,2449.27,2356.84,...,171648,26034,82,626.92,79,0.012742,0.020133,0.578650,7.373074,-0.734000
1,CAMP-0002,2025-01-03,FrameHouse,Facebook,Reel,25,Traffic,AR,1153.08,836.40,...,88732,22749,93,678.65,93,0.019998,0.025013,0.224960,4.498733,-0.188606
2,CAMP-0003,2025-01-04,PixelForge,Facebook,Video Largo,60,Ventas,PE,398.93,291.12,...,22772,9557,24,1082.33,63,0.009704,0.049180,0.596557,5.789055,2.717814
3,CAMP-0004,2025-01-05,FrameHouse,YouTube,Video Largo,90,Awareness,AR,1752.35,1304.59,...,177098,29152,19,64.42,69,0.008922,0.007627,0.523721,4.672383,-0.950621
4,CAMP-0005,2025-01-06,NeoStudio,Instagram,Video Largo,45,Ventas,CL,703.80,640.98,...,68165,39455,137,5787.29,73,0.013333,0.072950,0.341310,4.550605,8.028815

In [16]:
#Verificar que no haya valores nulos en ninguna de las  cinco columnas
print(f"Cantidad de valores nulos:\n{df.isna().sum()}")

Cantidad de valores nulos:
id_campana               0
fecha                    0
cliente                  0
plataforma               0
formato                  0
duracion_seg             0
objetivo                 0
pais                     0
presupuesto_usd          0
costo_usd                0
impresiones              0
alcance                  0
clicks                   0
reproducciones_3s        0
reproducciones_100       0
conversiones             0
ingresos_usd             0
calificacion_creativa    0
ctr                      0
cvr                      0
cpc                      0
cpm                      0
roi                      0
dtype: int64

## 4- Preguntas de negocio con filtros (Seccion 4)

In [ ]:
#Campañas con ROI negativo cuyo costo:usd esta encima de la mediana
df[(df.costo_usd > df.costo_usd.median())].sort_values('roi', ascending = False )

,id_campana,fecha,cliente,plataforma,formato,duracion_seg,objetivo,pais,presupuesto_usd,costo_usd,...,reproducciones_3s,reproducciones_100,conversiones,ingresos_usd,calificacion_creativa,ctr,cvr,cpc,cpm,roi
150,CAMP-0151,2025-06-01,PixelForge,TikTok,Story,5,Ventas,AR,1446.89,1432.64,...,311799,64308,944,49322.31,76,0.026206,0.074460,0.113002,2.961358,33.427567
54,CAMP-0055,2025-02-25,PixelForge,TikTok,Story,10,Ventas,AR,2158.86,1952.28,...,437914,115208,1222,60119.39,72,0.026451,0.073579,0.117551,3.109320,29.794451
158,CAMP-0159,2025-06-09,NeoStudio,TikTok,Reel,10,Ventas,CO,3472.48,2900.57,...,524059,134825,1656,84100.28,77,0.031839,0.058857,0.103091,3.282365,27.994398
100,CAMP-0101,2025-04-12,PixelForge,TikTok,Carrusel,0,Ventas,AR,3117.30,2218.04,...,195432,85354,1198,62497.38,82,0.021383,0.077360,0.143229,3.062715,27.176850
66,CAMP-0067,2025-03-09,NeoStudio,TikTok,Reel,15,Ventas,CO,2782.13,1882.76,...,258009,144902,962,46784.54,76,0.021614,0.082788,0.162028,3.502001,23.848913
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
167,CAMP-0168,2025-06-18,FrameHouse,Instagram,Video Largo,90,Awareness,CO,3127.85,2437.50,...,228910,38255,56,186.59,77,0.014069,0.007814,0.340100,4.784994,-0.923450
109,CAMP-0110,2025-04-21,LumaAds,Instagram,Imagen,0,Awareness,MX,1887.66,1418.09,...,81247,17243,36,106.33,64,0.012256,0.008229,0.324135,3.972619,-0.925019
14,CAMP-0015,2025-01-16,NeoStudio,X,Reel,10,Awareness,AR,3112.81,2981.28,...,245674,141110,66,214.46,74,0.015961,0.009700,0.438166,6.993697,-0.928064
13,CAMP-0014,2025-01-15,FrameHouse,YouTube,Reel,25,Awareness,PE,2386.46,2023.31,...,142472,28150,41,132.93,71,0.016858,0.007652,0.377624,6.366174,-0.934301
144,CAMP-0145,2025-05-26,CromaLab,Instagram,Imagen,0,Awareness,PE,1507.22,1422.27,...,81487,10230,29,92.61,71,0.012032,0.008222,0.403252,4.851796,-0.934886

In [42]:
#Plataformas en las que se encuentran más casos
df[df.costo_usd > df.costo_usd.median()]['plataforma'].value_counts()

plataforma
Instagram    24
TikTok       22
YouTube      18
Facebook     16
X            10
Name: count, dtype: int64

In [ ]:
#Top 10 campañas por ROI unicamente en Tiktok e Instagram
df[df['plataforma'].isin(['Tiktok', 'Instagram'])].sort_values('roi', ascending=False).head(10)

,id_campana,fecha,cliente,plataforma,formato,duracion_seg,objetivo,pais,presupuesto_usd,costo_usd,...,reproducciones_3s,reproducciones_100,conversiones,ingresos_usd,calificacion_creativa,ctr,cvr,cpc,cpm,roi
112,CAMP-0113,2025-04-24,FrameHouse,Instagram,Reel,25,Ventas,AR,955.30,690.79,...,76146,35503,220,10980.35,64,0.022548,0.053856,0.169104,3.812980,14.895352
64,CAMP-0065,2025-03-07,CromaLab,Instagram,Reel,20,Ventas,MX,1190.70,823.96,...,77066,29735,231,11299.92,78,0.017300,0.075392,0.268916,4.652303,12.714161
117,CAMP-0118,2025-04-29,FrameHouse,Instagram,Video Largo,120,Ventas,CL,1118.81,882.64,...,76761,33849,203,10390.17,69,0.013770,0.083265,0.362034,4.985371,10.771696
82,CAMP-0083,2025-03-25,FrameHouse,Instagram,Imagen,0,Ventas,CO,1430.76,1331.16,...,76961,8633,378,15629.22,89,0.013731,0.087642,0.308639,4.237798,10.741053
56,CAMP-0057,2025-02-27,PixelForge,Instagram,Reel,10,Ventas,CO,3176.73,2068.03,...,220030,94803,553,22576.13,74,0.016723,0.062303,0.232991,3.896422,9.916732
12,CAMP-0013,2025-01-14,FrameHouse,Instagram,Story,5,Ventas,CO,2680.92,1796.24,...,285090,49961,448,19192.94,66,0.020648,0.053691,0.215273,4.444994,9.685064
76,CAMP-0077,2025-03-19,PixelForge,Instagram,Story,10,Ventas,CO,2542.99,2052.22,...,179450,82544,456,21500.36,75,0.016720,0.084055,0.378289,6.324857,9.476635
75,CAMP-0076,2025-03-18,LumaAds,Instagram,Story,10,Ventas,CO,971.62,784.97,...,67914,39226,178,8049.85,79,0.015303,0.074884,0.330236,5.053661,9.254978
121,CAMP-0122,2025-05-03,NeoStudio,Instagram,Video Largo,90,Ventas,MX,2567.60,1742.66,...,142725,26672,438,17767.67,84,0.016193,0.088539,0.352266,5.704101,9.195718
42,CAMP-0043,2025-02-13,LumaAds,Instagram,Story,15,Ventas,PE,2297.57,2136.19,...,221582,113055,496,20797.09,74,0.014287,0.067862,0.292268,4.175720,8.735599

In [ ]:
#Formato que tenga CTR promedio mas alto
df.groupby('formato')['ctr'].mean().sort_values(ascending = False)

formato
Reel           0.020697
Story          0.018089
Carrusel       0.016975
Imagen         0.013379
Video Largo    0.013289
Name: ctr, dtype: float64

In [ ]:
#Pais que tiene mayor ingreso total
df.groupby('pais')['ingresos_usd'].sum().sort_values(ascending = False)

pais
CO    403762.10
AR    269396.00
MX    210840.92
CL    206504.35
PE    152053.80
Name: ingresos_usd, dtype: float64

## 5- Estadistica descriptiva: tendencia central (Seccion 5)

In [ ]:
#Metricas a analizar
metricas = ['costo_usd','impresiones','clicks','conversiones','ingresos_usd','ctr','cvr','cpc','cpm','roi']
#Dataframe de tendencia central, se tienen media, mediana y moda
tendencia_central = pd.DataFrame({
    'Media': df[metricas].mean(),
    'Mediana': df[metricas].median(),
    'Moda': df[metricas + ['plataforma', 'formato']].mode().iloc[0]
})

print(tendencia_central)

                      Media        Mediana       Moda
clicks          5601.138889    4433.500000        488
conversiones     221.577778     142.500000       41.0
costo_usd       1552.059222    1411.905000    2093.79
cpc                0.341340       0.291472   0.097611
cpm                5.040922       4.835617   2.961358
ctr                0.017121       0.016318   0.006095
cvr                0.040058       0.038661   0.008264
formato                 NaN            NaN       Reel
impresiones   320647.616667  307169.500000      42369
ingresos_usd    6903.095389    1864.945000      25.91
plataforma              NaN            NaN  Instagram
roi                3.498346       0.646721  -0.950621

In [ ]:
#Media de las plataformas
df.groupby('plataforma')[metricas].mean()

,costo_usd,impresiones,clicks,conversiones,ingresos_usd,ctr,cvr,cpc,cpm,roi
plataforma,,,,,,,,,,
Facebook,1483.649091,283566.909091,4666.242424,181.424242,4806.221515,0.016279,0.038923,0.336681,5.231254,2.167606
Instagram,1488.836809,304786.404255,5383.361702,193.829787,5423.360426,0.018006,0.039541,0.305394,4.868856,3.146111
TikTok,1659.795217,428032.347826,8930.130435,377.173913,13151.649130,0.021088,0.040195,0.224370,3.928090,6.672855
X,1713.446875,260552.750000,3298.375000,139.375000,4772.637500,0.012764,0.044180,0.553932,6.776648,1.769305
YouTube,1491.294211,267778.157895,3622.131579,137.026316,3887.259474,0.013790,0.039782,0.441927,5.704734,1.974836

In [ ]:
#Media de los formatos
df.groupby('formato')[metricas].mean()

,costo_usd,impresiones,clicks,conversiones,ingresos_usd,ctr,cvr,cpc,cpm,roi
formato,,,,,,,,,,
Carrusel,1466.786897,322712.827586,5727.310345,203.724138,5613.761034,0.016975,0.034329,0.333888,4.903621,2.265768
Imagen,1931.368621,390586.448276,5405.758621,201.620690,5124.717241,0.013379,0.039436,0.423699,5.190193,1.760106
Reel,1462.878727,313275.163636,6619.127273,249.490909,7495.124727,0.020697,0.037002,0.253811,4.843493,4.121491
Story,1555.031111,312971.444444,5829.416667,243.972222,8532.122500,0.018089,0.040377,0.331537,5.078947,4.606287
Video Largo,1431.764516,275283.419355,3594.677419,181.419355,6830.742903,0.013289,0.051052,0.437941,5.335845,3.885276

## 6- Estadistica descriptiva: dispersión (Seccion 5, continuacion)

In [ ]:
#Metricas a analizar
metricas = ['costo_usd','impresiones','clicks','conversiones','ingresos_usd','ctr','cvr','cpc','cpm','roi']
#Dataframe de dispersion, se tiene desviacion estandar, varianza, rango y rango IQR
dispersion = pd.DataFrame({
    'std': df[metricas].std(),
    'var': df[metricas].var(),
    'max - min': df[metricas].max() - df[metricas].min(),
    'Q3 - Q1': df[metricas].quantile(0.75) - df[metricas].quantile(0.25)
})

print(dispersion)

                        std           var      max - min        Q3 - Q1
costo_usd        876.228637  7.677766e+05    5814.060000    1232.820000
impresiones   182419.998948  3.327706e+10  867503.000000  237395.000000
clicks          4193.217039  1.758307e+07   27648.000000    4696.250000
conversiones     239.421532  5.732267e+04    1648.000000     226.250000
ingresos_usd   11625.027287  1.351413e+08   84074.370000    8280.960000
ctr                0.005161  2.663320e-05       0.027800       0.006665
cvr                0.024993  6.246660e-04       0.084922       0.040390
cpc                0.212825  4.529469e-02       1.873467       0.183360
cpm                1.330021  1.768956e+00       9.126577       1.624970
roi                6.321335  3.995928e+01      34.378188       5.685102

## 7- Deteccion de outliers con IQR (Seccion 6)

In [74]:
#Definir Q1, Q3 e IQR
q1_ctr = df.ctr.quantile(0.25)
q3_ctr = df.ctr.quantile(0.75)
IQR_ctr = q3_ctr - q1_ctr

#Definir limites inferior y superior
Q1 = q1_ctr - 1.5 * IQR_ctr
Q3 = q3_ctr + 1.5 * IQR_ctr

#Guardar los outliers en outliers_ctr
outliers_ctr = df[(df.ctr < Q1) | (df.ctr > Q3)]
print(f"Outliers: {len(outliers_ctr)}\n")

print(outliers_ctr)

Outliers: 3

    id_campana      fecha     cliente plataforma formato  duracion_seg  \
93   CAMP-0094 2025-04-05  FrameHouse     TikTok    Reel            30
108  CAMP-0109 2025-04-20   NeoStudio     TikTok    Reel            10
158  CAMP-0159 2025-06-09   NeoStudio     TikTok    Reel            10

      objetivo pais  presupuesto_usd  costo_usd  ...  reproducciones_3s  \
93   Awareness   PE          2569.17    2392.89  ...             447548
108  Awareness   PE           354.71     312.52  ...              33149
158     Ventas   CO          3472.48    2900.57  ...             524059

     reproducciones_100  conversiones  ingresos_usd  calificacion_creativa  \
93               125382           167        506.02                     83
108               13303            27         83.03                     89
158              134825          1656      84100.28                     77

          ctr       cvr       cpc       cpm        roi
93   0.032378  0.008005  0.114701  3.713822  -0.788532
108  0.033894  0.009009  0.104278  3.534415  -0.734321
158  0.031839  0.058857  0.103091  3.282365  27.994398

[3 rows x 23 columns]

1. Para outliers de ctr solo hay 3.
2. Los valores que tienen los outliers varian mucho dependiendo de la categoria, por ejemplo, en ingresos unos son valores altos, mientras que los demas son bajos, pero en las otras categorias, estos tienen valores que podrian considerarse elevados. En palabras simples, los valores no tienen tanta correlacion.
3. Las plataformas en las que se encuetran todos los outliers es en TIKTOK

In [76]:
#AHORA HACIENDO EL ANALISIS PARA ROI
#Definir Q1, Q3 e IQR
q1_roi = df.roi.quantile(0.25)
q3_roi = df.roi.quantile(0.75)
IQR_roi = q3_roi - q1_roi

#Definir limites inferior y superior
Q1 = q1_roi - 1.5 * IQR_roi
Q3 = q3_roi + 1.5 * IQR_roi

#Guardar los outliers en outliers_roi
outliers_roi = df[(df.roi < Q1) | (df.roi > Q3)]
print(f"Outliers: {len(outliers_roi)}\n")

print(outliers_roi)

Outliers: 12

    id_campana      fecha     cliente plataforma      formato  duracion_seg  \
19   CAMP-0020 2025-01-21    CromaLab     TikTok         Reel            10
22   CAMP-0023 2025-01-24  FrameHouse     TikTok       Imagen             0
31   CAMP-0032 2025-02-02     LumaAds     TikTok        Story            10
54   CAMP-0055 2025-02-25  PixelForge     TikTok        Story            10
66   CAMP-0067 2025-03-09   NeoStudio     TikTok         Reel            15
99   CAMP-0100 2025-04-11  FrameHouse    YouTube         Reel            20
100  CAMP-0101 2025-04-12  PixelForge     TikTok     Carrusel             0
112  CAMP-0113 2025-04-24  FrameHouse  Instagram         Reel            25
138  CAMP-0139 2025-05-20     LumaAds     TikTok         Reel            20
150  CAMP-0151 2025-06-01  PixelForge     TikTok        Story             5
157  CAMP-0158 2025-06-08   NeoStudio     TikTok  Video Largo            90
158  CAMP-0159 2025-06-09   NeoStudio     TikTok         Reel            10

    objetivo pais  presupuesto_usd  costo_usd  ...  reproducciones_3s  \
19    Ventas   MX          1098.95     937.63  ...             201724
22    Ventas   CO          1925.22    1677.89  ...              63564
31    Ventas   CL          1744.15    1227.09  ...             186500
54    Ventas   AR          2158.86    1952.28  ...             437914
66    Ventas   CO          2782.13    1882.76  ...             258009
99    Ventas   CO           266.84     224.85  ...              25385
100   Ventas   AR          3117.30    2218.04  ...             195432
112   Ventas   AR           955.30     690.79  ...              76146
138   Ventas   MX          1739.96    1535.43  ...             192421
150   Ventas   AR          1446.89    1432.64  ...             311799
157   Ventas   MX          1059.73    1057.54  ...             152145
158   Ventas   CO          3472.48    2900.57  ...             524059

     reproducciones_100  conversiones  ingresos_usd  calificacion_creativa  \
19                66975           420      22218.58                     62
22                10786           706      28810.28                     79
31                89677           465      21556.20                     70
54               115208          1222      60119.39                     72
66               144902           962      46784.54                     76
99                 5781            87       4580.14                     79
100               85354          1198      62497.38                     82
112               35503           220      10980.35                     64
138               44875           601      26374.02                     75
150               64308           944      49322.31                     76
157               73612           441      19772.16                     84
158              134825          1656      84100.28                     77

          ctr       cvr       cpc       cpm        roi
19   0.023523  0.056734  0.126655  2.979318  22.696533
22   0.021216  0.081637  0.194021  4.116380  16.170542
31   0.023939  0.071892  0.189717  4.541599  16.566927
54   0.026451  0.073579  0.117551  3.109320  29.794451
66   0.021614  0.082788  0.162028  3.502001  23.848913
99   0.020269  0.089048  0.230143  4.664841  19.369758
100  0.021383  0.077360  0.143229  3.062715  27.176850
112  0.022548  0.053856  0.169104  3.812980  14.895352
138  0.025734  0.061774  0.157820  4.061318  16.176960
150  0.026206  0.074460  0.113002  2.961358  33.427567
157  0.017460  0.087569  0.209996  3.666463  17.696371
158  0.031839  0.058857  0.103091  3.282365  27.994398

[12 rows x 23 columns]

## 8- Visualizacion (Seccion 7)